Repository decide-part-alberti-2/decide-part-alberti-2, pull requests merged in 2023-12, with the labels that each got.

#19 15 test implement census export
  decide/census/tests.py
Labels: test

#26 Fix: Changes pandas version
  .gitignore
  requirements.txt
Labels: bug

#29 Fix: Adds python-dotenv to requirements.txt
  requirements.txt
Labels: bug

#31 Hotfix/1 implement authentication by email
  decide/authentication/forms.py
  decide/authentication/templates/login.html
  decide/authentication/templates/register.html
  decide/authentication/templates/register_done.html
  decide/authentication/tests.py
  decide/authentication/urls.py
  decide/authentication/views.py
Labels: bug

#39 Hotfix/module census
  decide/base/tests.py
  decide/census/admin.py
  decide/census/templates/import_census_form.html
  decide/census/tests.py
Labels: test

#40 Test/1 implement authentication by email
  decide/authentication/tests.py
  decide/locustfile.py
Labels: Medium-priority, test

#44 Fix/Refactor: Solves issues on Codacy
  decide/authentication/views.py
Labels: bug

#50 48 implement deployment on render
  .github/workflows/render.yml
  decide/decide/settings.py
  decide/launch.sh
  decide/local_settings.deploy.py
  decide/nginx.conf
  requirements.txt
Labels: enhancement, High-priority

#52 Hotfix/48 implement deployment on render
  .github/workflows/django.yml
  decide/decide/settings.py
Labels: bug

#54 Fix: Solves issue on LDAP import
  decide/census/templates/LDAPvotacion.html
  decide/census/tests.py
  decide/census/views.py
Labels: bug

#56 Fix: created file in tests now get deleted
  decide/census/tests.py
Labels: bug

#58 Hotfix/docker and vagrant
  decide/decide/settings.py
  docker/docker-compose.yml
Labels: bug, High-priority

#60 Release/v1.1.0
  .github/workflows/release.yml
  .github/workflows/render.yml
  .gitmessage.txt
  README.md
  decide/authentication/templates/logout.html
  decide/authentication/urls.py
  decide/authentication/views.py
  decide/census/forms.py
  decide/census/models.py
  decide/census/templates/LDAPvotacion.html
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
  decide/decide/settings.py
  decide/launch.sh
  decide/local_settings.deploy.py
  decide/nginx.conf
  docker/docker-compose.yml
  requirements.txt
Labels: enhancement

#62 61 feature change register title
  .github/workflows/django.yml
  .github/workflows/release.yml
  .github/workflows/render.yml
  README.md
  decide/authentication/templates/register.html
  decide/decide/settings.py
Labels: enhancement, High-priority
